### ISSUE TITLE
Template repo

### ISSUE THREAD

**Issue by FabienDanieau** [pollen-robotics/python-coding-guidelines#7]
Make this repo a template (a priori not possible because it contains LFS files) or create a new one

**Comment by FabienDanieau** [comment]
@RemiFabre @pierre-rouanet I think the best solution is to make a new repo without LFS (there is not much but it is a pain to remove it completely). And then to make this repo a template. There is nothing important in the history (which does not follow a clone from a template anyway)

**Comment by RemiFabre** [comment]
Please ping me when this is done

**Comment by FabienDanieau** [comment]
Done: see https://github.com/pollen-robotics/python-template
I'll make this repo as an archive
